server:
  external_url: "http://localhost:8080"
oauth2:
  idp:
    type: "local"
    local:
      users:
        - username: "admin@example.com"
          password: "${MCP_ADMIN_PASSWORD}"
zomboid:
  instances:
    - name: "foo"
      home_dir: "/tmp/foo"
      users:
        - "admin@example.com"
    - name: "bar"
      home_dir: "/tmp/bar"
      users:
        - "user@example.com"