logger:
  json_format: false
  disable_color: false
server:
  port: 8080
  external_url: ""
oauth2:
  signing_secret: ""
  id_token_signing_key: ""
  pending_auth_ttl: 10m
  idp:
    type: "local"
    local:
      users:
        - username: ""
          password: ""
